/* data actions */
export const FETCH_FEED_COMPANY = 'FETCH_FEED_COMPANY'
export const UPDATE_FEED_DATA = 'UPDATE_FEED_DATA'

export const FETCH_COMPANY_DATA = 'FETCH_COMPANY_DATA'
export const UPDATE_COMPANY_DATA = 'UPDATE_COMPANY_DATA'
export const SORT_COMPANY_DATA = 'SORT_COMPANY_DATA'
export const FETCH_COMPANY = 'FETCH_COMPANY'

export const FETCH_PRODUCT_DATA = 'FETCH_PRODUCT_DATA'
export const UPDATE_PRODUCT_DATA = 'UPDATE_PRODUCT_DATA'
export const FETCH_PRODUCT = 'FETCH_PRODUCT'

//Filter Actions
export const FILTER_FEED_SEARCH = 'FILTER_FEED_SEARCH'
export const FILTER_FEED_DROPDOWN = 'FILTER_FEED_DROPDOWN'
export const FILTER_FEED_DATE = 'FILTER_FEED_DATE'
export const CLEAR_FEED_DROPDOWN = 'CLEAR_FEED_DROPDOWN'

export const FILTER_COMPANY_NAME = 'FILTER_COMPANY_NAME'
export const FILTER_COMPANY_DESCRIPTION = 'FILTER_COMPANY_DESCRIPTION'
export const FILTER_COMPANY_DROPDOWNOPTIONS = 'FILTER_COMPANY_DROPDOWNOPTIONS'
export const FILL_COMPANY_COLUMN = 'FILL_COMPANY_COLUMN'
export const FILTER_COMPANY_SLIDERS = 'FILTER_COMPANY_SLIDERS'
export const CLEAR_COMPANY_DROPDOWNOPTIONS = 'CLEAR_COMPANY_DROPDOWNOPTIONS'
export const CLEAR_COMPANY_SLIDERS = 'CLEAR_COMPANY_SLIDERS'
export const CLEAR_COMPANY_ALL = 'CLEAR_COMPANY_ALL'
export const CHANGE_RANK_WEIGHTS = 'CHANGE_RANK_WEIGHTS'

export const FILTER_PRODUCT_NAME = 'FILTER_PRODUCT_NAME'
export const FILTER_PRODUCT_DROPDOWNOPTIONS = 'FILTER_PRODUCT_DROPDOWNOPTIONS'
export const FILL_PRODUCT_COLUMN = 'FILL_PRODUCT_COLUMN'
export const CLEAR_PRODUCT_DROPDOWNOPTIONS = 'CLEAR_PRODUCT_DROPDOWNOPTIONS'
export const CLEAR_PRODUCT_ALL = 'CLEAR_PRODUCT_ALL'

/* pagination actions */
export const CHANGE_PAGE_NUMBER = 'CHANGE_PAGE_NUMBER'
export const CHANGE_LAST_PAGE_NUMBER = 'CHANGE_LAST_PAGE_NUMBER'
